name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install pre-requisites
      run: sudo apt install gcc-riscv64-unknown-elf binutils-riscv64-unknown-elf
    - name: Run tests
      run: cargo test -- --nocapture
